# Generated by Django 4.1.7 on 2023-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_portfolio_img_alter_service_portfolio_examples_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='Img',
            field=models.ImageField(blank=True, upload_to='static/assets/img/'),
        ),
    ]
