# Generated by Django 4.1.7 on 2023-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_teammember_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='desProjets',
            field=models.URLField(blank=True),
        ),
    ]
