# Generated by Django 4.1.7 on 2023-05-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_teammember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Img',
            field=models.ImageField(blank=True, upload_to='static/assets/img/'),
        ),
    ]
