# Generated by Django 4.1.7 on 2023-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projectrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('contact', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='contact_name',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='projectrequest',
            name='phone',
        ),
    ]
