# Generated by Django 4.1.7 on 2023-03-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
